# syntax=docker/dockerfile:1

# First stage: build
FROM python:3.9.16-alpine3.17 AS build

# Set working directory
WORKDIR /app

# Copy files
COPY app.py .
COPY src /app/src
COPY requirements.txt /.

# Install dependencies and create binary wheel files for them
RUN pip install --no-cache-dir --upgrade pip && \
    pip wheel --no-cache-dir --wheel-dir=/usr/src/app/wheels -r /requirements.txt

# Second stage: release
FROM python:3.9.16-alpine3.17 AS release

# Set working directory
WORKDIR /app

# Copy wheel files from build stage
COPY --from=build /usr/src/app/wheels /usr/src/app/wheels

# Install dependencies from wheels
RUN pip install --no-cache /usr/src/app/wheels/*

# Copy source files from build stage
COPY --from=build /app .

# Expose port
EXPOSE 8080

# Create non-root user
RUN adduser -u 10001 -D nonroot

# Run app as non-root user
USER nonroot
CMD [ "python", "app.py" ]
