# syntax=docker/dockerfile:1

# Base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy files
COPY app.py .
COPY src /app/src
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8080

# Run app
CMD [ "python", "app.py" ]
