version: "3.9"
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      MONGO_URI: mongodb://mongo:27017/test
    ports:
      - "8080:8080"
    depends_on:
      - mongo
